### PR TITLE
Feature/sortpotential

### PR DESCRIPTION
**Pull request by MaxOstrowski**
Is there anything missing ? Evaluation is still unclear, no ?

### CODE REVIEW

**Comment by MaxOstrowski** [comment]
What about default value...

**Comment by rkaminsk** [comment]
You might want to benchmark again. Sorting by potential was broken.

**Comment by MaxOstrowski** [comment]
Was it ? Couldn't figure what was broken in th issue, but will just run them again...

**Comment by rkaminsk** [comment]
> Was it ? Couldn't figure what was broken in the issue [...]

I would think that the expression `get_potential(edge) + edge.weight - get_potential(edge)` evaluates to `edge.weight`.

**Comment by MaxOstrowski** [comment]
Well, my awesomeness striked again. :man_facepalming:

**Comment by MaxOstrowski** [comment]
[results.zip](https://github.com/potassco/clingoDL/files/4415476/results.zip)

Looks good, reversed potential has some potential.

**Pull request merged**
